# Environment for Hybrid CNN-Vision Transformer pollen grain classification (CoAtNet and Swin/ConvNeXt models)
name: pollen_classification_env 
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - opencv
  - numpy
  - matplotlib 
  - scikit-learn 
  - pillow 
  - pyyaml 
  - tqdm 
  - pandas 
  - timm
  - seaborn

    
