# Environment for YOLO-based pollen grain detection
name: yolo_detection_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8 
  
  - numpy
  - matplotlib
  - pillow
  - pyyaml
  - tqdm
  - pandas
  - scikit-learn
  - timm
  - pip:
    - ultralytics
    - opencv-python