name: honey_auth_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  # PyTorch and related
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8  # This needs the 'nvidia' channel
  # Ultralytics (YOLO)
  - ultralytics
  # Other core libraries
  - opencv
  - numpy
  - matplotlib
  - scikit-learn
  - pillow
  - pyyaml
  - tqdm
  - pandas
  - timm
  - pip:
      # Add any pip-only packages here
      # - some-pip-only-package
