# Environment file for MMDetection-based pollen grain detection
name: mmdetection_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pytorch=2.1.0 
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - numpy
  - matplotlib
  - pillow
  - pyyaml
  - tqdm
  - pandas
  - scikit-learn
  
