# Environment file for MMDetection-based pollen grain detection
name: mmdetection_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  # --- Core Conda Dependencies ---
  - python=3.9
  - pip
  # Pin the specific PyTorch and CUDA versions for reproducibility
  - pytorch=2.1.0 
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8

  # --- Common Python Libraries ---
  - numpy
  - matplotlib
  - pillow
  - pyyaml
  - tqdm
  - pandas
  - scikit-learn
  
