# Environment file for YOLOX training with MMDetection
name: yolox_mmdet_env
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pytorch=2.1.2
  - torchvision=0.16.2
  - torchaudio=2.1.2
  - pytorch-cuda=11.8
  - cython
  - matplotlib
  - pycocotools
  - tqdm
  - openmim
  - pip:
    - mmcv==2.1.0
    - mmdet==3.3.0
    - label-studio-sdk
    - pyarrow