# File: configs/dataset/deim_detection.yml

task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

num_classes: 1 
remap_mscoco_category: False # Crucial for custom datasets

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /scratch/rmkyas002/deim_data/images/train
    ann_file: /scratch/rmkyas002/deim_data/annotations/instances_train.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 1
  drop_last: True
  collate_fn:
    type: BatchImageCollateFunction

val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /scratch/rmkyas002/deim_data/images/val
    ann_file: /scratch/rmkyas002/deim_data/annotations/instances_val.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  num_workers: 1
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction


test_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /scratch/rmkyas002/deim_data/images/test
    ann_file: /scratch/rmkyas002/deim_data/annotations/instances_test.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  num_workers: 1
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction